name: Build PDF with Make

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Makefile'
      - 'atelier_vr.tex'
      - '**/*.tex'
      - 'tex/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install TeX Live and Pygments
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make latexmk \
            texlive-latex-recommended texlive-latex-extra \
            texlive-fonts-recommended texlive-fonts-extra \
            texlive-lang-french texlive-xetex \
            python3-pygments

      - name: Verify pygmentize
        run: pygmentize -V

      # ✅ NEW: create atelier_vr.pyg only if missing (no repo changes needed)
      - name: Ensure minted input files exist
        run: |
          if [ ! -f atelier_vr.pyg ]; then
            printf '%s\n' '<!-- placeholder created in CI so \inputminted can read it -->' > atelier_vr.pyg
          fi

      - name: Build PDF with Make
        run: make

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: atelier_vr-pdf
          path: |
            **/atelier_vr.pdf
          if-no-files-found: error
