name: Build PDF (minted)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Makefile'
      - '**/*.tex'
      - '**/*.sty'
      - '**/*.cls'
      - '**/*.bib'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.pdf'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installe TeX Live (latexmk + paquets utiles) et Pygments
      - name: Install TeX Live and Pygments
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make latexmk \
            texlive-latex-recommended texlive-latex-extra \
            texlive-fonts-recommended texlive-fonts-extra \
            texlive-lang-french texlive-xetex \
            python3-pygments

      # Si ton Makefile a une cible "venv", on la lance (sinon, ça passe).
      - name: (Optional) Set up Python venv via Makefile
        run: make venv || true

      # Petit check que pygmentize est bien dispo
      - name: Verify pygmentize
        run: pygmentize -V

      # Compile via ton Makefile (qui inclut déjà -shell-escape)
      - name: Build PDF with Make
        run: make

      # Aide debug : lister le cache minted
      - name: List minted cache (debug)
        if: always()
        run: ls -alR build/_minted-* || true

      # Publie le PDF (où qu’il soit : racine ou build/)
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: atelier_vr-pdf
          path: |
            **/atelier_vr.pdf
          if-no-files-found: error
