name: Build PDF with Make

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Makefile'
      - 'atelier_vr.tex'
      - '**/*.tex'
      - 'tex/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installe un environnement LaTeX raisonnable (latexmk + packages courants)
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make latexmk \
            texlive-latex-recommended texlive-latex-extra \
            texlive-fonts-recommended texlive-fonts-extra \
            texlive-lang-french texlive-xetex

      # Lance make (si ta cible n'est pas la cible par défaut, remplace par: make atelier_vr.pdf)
      - name: Build PDF with Make
        run: make

      # Publie le PDF compilé comme artifact téléchargeable depuis la page du run
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: atelier_vr-pdf
          path: |
            **/atelier_vr.pdf
          if-no-files-found: error

  # Optionnel : créer automatiquement une Release quand tu pousses un tag (ex: v1.0.0)
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: atelier_vr-pdf
          path: .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            atelier_vr.pdf
