name: Build PDF with Make

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Makefile'
      - 'atelier_vr.tex'
      - '**/*.tex'
      - 'tex/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ Install TeX Live + Pygments (needed by minted)
      - name: Install TeX Live and Pygments
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make latexmk \
            texlive-latex-recommended texlive-latex-extra \
            texlive-fonts-recommended texlive-fonts-extra \
            texlive-lang-french texlive-xetex \
            python3-pygments

      # (Optional) If your Makefile has a 'venv' target that installs pygments, keep it:
      - name: (Optional) Set up Python venv via Makefile
        run: make venv || true

      - name: Verify pygmentize is available
        run: pygmentize -V

      # Your Makefile already uses -shell-escape — perfect.
      - name: Build PDF with Make
        run: make

      # Helpful for diagnosing minted path issues if something goes wrong
      - name: List minted cache (debug)
        if: always()
        run: ls -alR build/_minted-* || true

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: atelier_vr-pdf
          path: |
            **/atelier_vr.pdf
          if-no-files-found: error

  # Optional: Release on tags
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: atelier_vr-pdf
          path: .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            atelier_vr.pdf
